### ISSUE TITLE
Cpu session out of metadata

### ISSUE THREAD

**Issue by BugUser0815** [702nADOS/genode#13]
@StefanEdingerTUM since I merged your new cpu thread component I get this error:
[init] Uncaught exception of type 'N6Genode11Cpu_session15Out_of_metadataE' (use 'c++filt -t' to demangle)
@dk87 would you also be so kind to take a look at what is wrong here?
My commits are all working fine, until I merge Stefan's code.

**Comment by StefanEdingerTUM** [comment]
@BugUser0815 I pulled from genode and prepard focnados again, but now i get a compile error: /vagrant/genode/repos/base-focnados/src/core/platform_thread.cc:389:45: error: ‘l4_scheduler_get_dead’ was not declared in this scope
  l4_scheduler_get_dead(L4_BASE_SCHEDULER_CAP)
Nevertheless, I corrected an error within the session_component. Could you please try again?

**Comment by BugUser0815** [comment]
@StefanEdingerTUM I updated foc, so you have to prepare foc again to download the new version.
Unfortunately the error is still there and still the same.
